@baseUrl = http://localhost:7002
@token = system<<.>>95424246-84c3-4e80-9462-f7b69e565e75

###
POST {{baseUrl}}/chat/send/text
accept: application/json
token: {{token}}
Content-Type: application/json

{
   "Phone": "554784080056",
    "Body": "How you doin",
   // "Id": "ABCDABALDJLJDASD89",
    "ContextInfo": {
       // "StanzaId": "3EB06F9067F80BAB89FF",
       // "Participant": "554784080056@s.whatsapp.net"
    }
}





###
POST {{baseUrl}}/chat/send/media
Content-Type: application/json
accept: application/json
token: {{token}}

{
   "Phone": "554784080056",
   "MediaUrl": "https://pa2025dev-r2.possoatender.com/system/documents/temp/sent-messages/1739296807455/audio_message.ogg",
   "Caption": "Check out this image!",
   "MediaType": "audio",
   "ContextInfo": {
       // "StanzaId": "3EB06F9067F80BAB89FF",
       // "Participant": "554784080056@s.whatsapp.net"
   }
}


